//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Category
{
    public Category()
    {
        this.Products = new HashSet<Product>();
        this.Finds = new HashSet<Find>();
    }

    public int CategoryID { get; set; }
    public string Category_Name { get; set; }

    public virtual ICollection<Product> Products { get; set; }
    public virtual ICollection<Find> Finds { get; set; }
}

public partial class Comment
{
    public int CommentID { get; set; }
    public string Comment1 { get; set; }
    public int ProductID { get; set; }
    public int UserID { get; set; }
    public string Link { get; set; }

    public virtual Product Product { get; set; }
    public virtual Userdata Userdata { get; set; }
}

public partial class Country
{
    public Country()
    {
        this.Products = new HashSet<Product>();
        this.Userdatas = new HashSet<Userdata>();
    }

    public int CountryID { get; set; }
    public string Country_Name { get; set; }

    public virtual ICollection<Product> Products { get; set; }
    public virtual ICollection<Userdata> Userdatas { get; set; }
}

public partial class Find
{
    public int ItemID { get; set; }
    public string ItemName { get; set; }
    public string ItemImage { get; set; }
    public string ItemDescription { get; set; }
    public string ItemPrice { get; set; }
    public Nullable<int> ProductID { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public string Link { get; set; }
    public string Date { get; set; }

    public virtual Category Category { get; set; }
    public virtual Product Product { get; set; }
}

public partial class Like
{
    public int LikeID { get; set; }
    public int UserID { get; set; }
    public int ProductID { get; set; }

    public virtual Product Product { get; set; }
    public virtual Userdata Userdata { get; set; }
}

public partial class Product
{
    public Product()
    {
        this.Comments = new HashSet<Comment>();
        this.Reports = new HashSet<Report>();
        this.Likes = new HashSet<Like>();
        this.Finds = new HashSet<Find>();
    }

    public int ProductID { get; set; }
    public string Product_Name { get; set; }
    public string Image { get; set; }
    public Nullable<int> Budget { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public Nullable<int> CountryID { get; set; }
    public Nullable<int> UserID { get; set; }
    public string ProductDescription { get; set; }

    public virtual Category Category { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual Country Country { get; set; }
    public virtual Userdata Userdata { get; set; }
    public virtual ICollection<Report> Reports { get; set; }
    public virtual ICollection<Like> Likes { get; set; }
    public virtual ICollection<Find> Finds { get; set; }
}

public partial class Report
{
    public int ReportID { get; set; }
    public Nullable<int> ProductID { get; set; }

    public virtual Product Product { get; set; }
}

public partial class Userdata
{
    public Userdata()
    {
        this.Comments = new HashSet<Comment>();
        this.Products = new HashSet<Product>();
        this.Likes = new HashSet<Like>();
    }

    public int UserID { get; set; }
    public string Username { get; set; }
    public string Email { get; set; }
    public string Type { get; set; }
    public int CountryID { get; set; }
    public string Gender { get; set; }

    public virtual ICollection<Comment> Comments { get; set; }
    public virtual Country Country { get; set; }
    public virtual ICollection<Product> Products { get; set; }
    public virtual ICollection<Like> Likes { get; set; }
}

public partial class Login_Check_Sp_Result
{
    public int UserID { get; set; }
    public string Username { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string Type { get; set; }
    public int CountryID { get; set; }
}

public partial class SP_DeleteComment_Result
{
    public int CommentID { get; set; }
    public string Comment { get; set; }
    public int ProductID { get; set; }
    public int UserID { get; set; }
}

public partial class SP_GetAllCategories_Result
{
    public int CategoryID { get; set; }
    public string Category_Name { get; set; }
}

public partial class SP_GetAllCountries_Result
{
    public int CountryID { get; set; }
    public string Country_Name { get; set; }
}

public partial class SP_LikeCheck_Result
{
    public int UserID { get; set; }
    public int ProductID { get; set; }
}

public partial class SP_userCheck_Result
{
    public int ProductID { get; set; }
    public string Product_Name { get; set; }
    public string Image { get; set; }
    public Nullable<int> Budget { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public Nullable<int> CountryID { get; set; }
    public Nullable<int> UserID { get; set; }
    public string ProductDescription { get; set; }
}

public partial class SP_UserPosts_Result
{
    public int ProductID { get; set; }
    public string Product_Name { get; set; }
    public string Image { get; set; }
    public Nullable<int> Budget { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public Nullable<int> CountryID { get; set; }
    public Nullable<int> UserID { get; set; }
    public string ProductDescription { get; set; }
}

public partial class spSearch_Result
{
    public int ProductID { get; set; }
    public string Product_Name { get; set; }
    public string Image { get; set; }
    public Nullable<int> Budget { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public Nullable<int> CountryID { get; set; }
    public Nullable<int> UserID { get; set; }
    public string ProductDescription { get; set; }
}

public partial class User_Check_Sp_Result
{
    public int UserID { get; set; }
    public string Username { get; set; }
    public string Email { get; set; }
    public string Gender { get; set; }
    public string Type { get; set; }
    public int CountryID { get; set; }
}
